### PR TITLE
Fixes #27 Removed the error from MessageBox

### LINKED ISSUE #27: Error in strokeWidth of MessageView
### Before reporting an issue I am agreeing to the points below
- [ ] I'm running my app on SDK level > 21.
- [ ] Target SDK version on my machine is 28.
- [ ] I haven't altered the default Gradle configuration for the app.

### Description
The StrokeWidth attribute in MessageBox is not accepting 5dp or any value 

### Steps to reproduce the behavior:
1. Go to 'run the application directly '
2. Click on ' Build'
3. Scroll down to 'here you will see the cause of error'
4. See an error

### Expected behavior
Run perfectly and the message box stroke width should be 5dp
.

## Platform Info
 - Device: [Samsung A30]
 - OS: [Android 10]

**Additional context**

### PR DESCRIPTION
**Pull request by Nikhilkumar25**
I removed the error from the messageBox (Stroke width)

### CODE REVIEW

**Comment by noman2002** [comment]
@Nikhilkumar25  Please discuss the changes in the issue section before making a PR.
Thanks!!

**Comment by Nikhilkumar25** [comment]
sorry,
in the above PR 
there was an error in the stroke width
because it accepts float value but getDimension was not the right for that 
I changed it to getFloat and now its working

**Comment by noman2002** [comment]
Please create a issue for that and link it with this PR.

**Comment by Nikhilkumar25** [comment]
#27

**Comment by noman2002** [comment]
Hello @Nikhilkumar25 , please change the title to Fixes #<issue number> removed the error from MessageBox .
Make sure that each PR is linked to an issue.
Thanks!!

**Review by altruisticdream — APPROVED** [review]

**Pull request closed without merging**
