### PR TITLE
Fixes #19 Variable password strength bar

### LINKED ISSUE #19: Variable password strength bar
### Title or Name of the custom view
Variable password strength bar 

### Description of the view
This patch allows developer to specify a variable number of progressbars and automatically sets the 
range of colors from RED:weakest to GREEN:strongest.

**Possible Approach(If any)**
A custom view that draws the required rectangles and fills up with colors. 

**Additional context**
Add any other context or screenshots or prototype about the feature request here.

### PR DESCRIPTION
**Pull request by ekrmh**
Fix #19 

### Usage

Define **PasswordStrengthBar** in your xml file.

```xml
<com.example.customviewdemoapplication.Views.password_strength.PasswordStrengthBar
            android:id="@+id/passwordStrengthBar"
            android:layout_width="200dp"
            android:layout_height="5dp"
            android:layout_margin="8dp"
            app:cornerRadius="8dp"
            app:password="password123"
            app:maxLength="15"
            app:minLength="6" />
```

Background drawable radius value. **Default value is 0.** 
```xml
     app:cornerRadius="8dp"
```
Min and max password length.
If the password that user entered lower than min length then password strength will be WEAK.
**Default Min Length:  8
Default Max Length: 15**
```xml
     app:maxLength="15"
     app:minLength="6"
```
Default password can be set in XML file.
```xml
      app:password="password123"
```

setPassword function calculate password strength and update UI.  Developers can get password strength when password changed by adding **PasswordStrengthChangeListener**.

**PasswordStrength**
This class is a enum class. It represents strength of password.

- WEAK,
- MEDIUM
- STRONG,
- VERY_STRONG

```java
        PasswordStrengthBar passwordStrengthBar = findViewById(R.id.passwordStrengthBar);
        passwordStrengthBar.addPasswordStrengthChangeListener(new PasswordStrengthChangeListener() {
            @Override
            public void onPasswordStrengthChanged(PasswordStrength passwordStrength) {
                textView.setText("Password Strength: " + passwordStrength.name());
            }
        });

        passwordStrengthBar.setPassword("Password");
```

### Test

my_gif

### CODE REVIEW

**Comment by noman2002** [comment]
Hello @ekrmh , please change the title to Fixes #<issue number> Variable password strength bar.
Thanks!!

**Comment by ekrmh** [comment]
> Hello @ekrmh , please change the title to Fixes # Variable password strength bar.
> Thanks!!

Changed

**Comment by noman2002** [comment]
@ekrmh Please update the readme file and also attach the screenshot (don't change the code just replace the screenshot).

**Comment by ekrmh** [comment]
> 
> 
> @ekrmh Please update the readme file and also attach the screenshot (don't change the code just replace the screenshot).

I've updated README file and attached the screenshot.

**Comment by noman2002** [comment]
Great @ekrmh , It will be reviewed soon. Just wait for some time.
Thanks!!

**Review by abhi114 — APPROVED** [review]

**Comment by noman2002** [comment]
Great work @ekrmh , I hope a lot more contribution from your side.
Good Luck.

**Pull request merged**
